language: java
install: true
dist: bionic

jdk:
  - oraclejdk8

services:
  - mysql

addons:
  apt:
    packages:
    - wget2

script:
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - mysql -e "CREATE DATABASE dbvergilius; CREATE USER 'vergilius' IDENTIFIED BY '3034'; GRANT ALL PRIVILEGES ON dbvergilius.* TO 'vergilius'; FLUSH PRIVILEGES;"
      - ./gradlew bootRun &
      - sleep 20s
      - wget2 --mirror --page-requisites -E http://127.0.0.1:8080/
      - jobs -p | xargs kill -9
    on:
      branch: release
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    repo: VergiliusProject/vergiliusproject-test.github.io
    target_branch: master
    local_dir: 127.0.0.1
    on:
      branch: release